/**
 * Contest API Types
 *
 * AUTO-GENERATED by scripts/merge-types.ts - DO NOT EDIT
 *
 * This file is merged from the spec-version-specific contest-types-*.ts files.
 * It includes types from the 2023-06,2026-01,2026-01-next Contest API specifications,
 * and CDS extensions.
 * Inline comments are used to indicate objects and properties that are unique to any of these.
 */

export type ContestType =
	| 'version'
	| 'access'
	| 'contest'
	| 'judgement-types'
	| 'languages'
	| 'problems'
	| 'groups'
	| 'organizations'
	| 'teams'
	| 'persons'
	| 'account'
	| 'accounts'
	| 'state'
	| 'submissions'
	| 'judgements'
	| 'runs'
	| 'clarifications'
	| 'awards'
	| 'commentary'
	| 'scoreboard'
	| 'map-info'
	| 'start-status';

export type Id = string;

export type RelTime = string;

export type Time = string;

export interface Provider {
	name: string;
	version?: string;
	logo?: FileReference[];
}

export interface Version {
	version: string;
	version_url: string;
	provider?: Provider;
}

export interface Access {
	capabilities: string[];
	endpoints: Endpoint[];
}

export interface Endpoint {
	type: string;
	properties: string[];
}

export interface Location {
	latitude: number;
	longitude: number;
}

export interface Contest {
	id: Id;
	name: string;
	formal_name?: string;
	start_time?: string;
	countdown_pause_time?: RelTime;
	duration: RelTime;
	scoreboard_freeze_duration?: RelTime;
	scoreboard_thaw_time?: Time;
	scoreboard_type: 'pass-fail' | 'score';
	penalty_time?: number | RelTime; // 2023-06 | 2026-01 spec
	main_scoreboard_group_id?: Id; // 2026-01 spec
	banner?: FileReference[];
	logo?: FileReference[];
	location?: Location;
	time_multiplier?: number; // CDS extension
}

export interface FileReference {
	href: string;
	filename: string;
	mime: string;
	hash?: string;
	width?: number;
	height?: number;
	tag?: string[]; // 2026-01 spec
}

export interface ContestState {
	started?: Time;
	frozen?: Time;
	ended?: Time;
	thawed?: Time;
	finalized?: Time;
	end_of_updates?: Time;
	removed_intervals?: RemovedInterval[]; // 2026-01-next spec
}

export interface TeamLocation {
	x: number;
	y: number;
	rotation: number;
}

export interface Team {
	id: Id;
	icpc_id?: string;
	label: string;
	name: string;
	display_name?: string;
	organization_id?: string;
	group_ids?: string[];
	hidden?: boolean; // 2023-06 spec
	photo?: FileReference[];
	video?: FileReference[];
	backup?: FileReference[];
	key_log?: FileReference[];
	tool_data?: FileReference[];
	desktop?: FileReference[];
	webcam?: FileReference[];
	audio?: FileReference[];
	location?: TeamLocation;
	primary_rgb?: string; // 2026-01-next spec
	primary_color?: string; // 2026-01-next spec
	secondary_rgb?: string; // 2026-01-next spec
	secondary_color?: string; // 2026-01-next spec
}

export interface Problem {
	id: Id;
	uuid?: string;
	label: string;
	name: string;
	ordinal: number;
	rgb?: string;
	color?: string;
	time_limit: number;
	test_data_count: number;
	max_score?: number;
	package?: FileReference[];
	statement?: FileReference[];
	memory_limit?: number; // 2026-01 spec
	output_limit?: number; // 2026-01 spec
	code_limit?: number; // 2026-01 spec
	attachments?: FileReference[]; // 2026-01 spec
	location?: FloorLocation; // CDS extension
}

export interface Group {
	id: Id;
	icpc_id?: string;
	name: string;
	type?: string;
	location?: Location;
	logo?: FileReference[]; // CDS extension
}

export interface Organization {
	id: Id;
	icpc_id?: string;
	name: string;
	formal_name?: string;
	country?: string;
	country_flag?: FileReference[];
	country_subdivision?: string; // 2026-01 spec
	country_subdivision_flag?: FileReference[]; // 2026-01 spec
	twitter_hashtag?: string;
	twitter_account?: string;
	url?: string;
	logo?: FileReference[];
	location?: Location;
	audio?: FileReference[]; // CDS extension
}

export interface Submission {
	id: Id;
	language_id: Id;
	problem_id: Id;
	team_id?: Id;
	account_id?: Id; // 2026-01 spec
	time: Time;
	contest_time: RelTime;
	entry_point?: string;
	files: FileReference[];
	reaction?: FileReference[];
}

export interface JudgementType {
	id: Id;
	simplified_judgement_type_id?: Id; // 2026-01 spec
	name: string;
	penalty: boolean;
	solved: boolean;
}

export interface Language {
	id: Id;
	name: string;
}

export interface Person {
	id: Id;
	icpc_id?: string;
	name: string;
	team_ids?: Id[]; // 2023-06 spec
	title?: string; // 2023-06 spec
	email?: string;
	sex?: string | 'male' | 'female'; // 2023-06 | 2026-01-next spec
	roles?: PersonRole[]; // 2026-01-next spec
	role?: 'contestant' | 'coach' | 'staff' | 'other'; // 2023-06 spec
	photo?: FileReference[];
}

export interface Scoreboard {
	time: Time;
	contest_time: RelTime;
	state: ContestState;
	rows: ScoreboardRow[];
}

export interface ScoreboardScore {
	num_solved?: number;
	score?: number;
	time?: number | RelTime; // 2023-06 | 2026-01 spec
	total_time?: number | RelTime; // 2023-06 | 2026-01 spec
}

export interface ScoreboardRow {
	rank: number;
	team_id: Id;
	score: ScoreboardScore;
	problems?: ScoreboardProblem[];
}

export interface ScoreboardProblem {
	problem_id: Id;
	num_judged: number;
	num_pending: number;
	solved?: boolean;
	score?: number;
	time?: number | RelTime; // 2023-06 | 2026-01 spec
}

export interface Judgement {
	id: Id;
	submission_id: Id;
	judgement_type_id?: Id;
	simplified_judgement_type_id?: Id; // 2026-01 spec
	score?: number;
	current?: boolean; // 2026-01 spec
	start_time: Time;
	start_contest_time?: RelTime; // 2023-06 spec
	end_time?: Time;
	end_contest_time?: RelTime; // 2023-06 spec
	max_run_time?: number;
}

export interface Run {
	id: Id;
	judgement_id: Id;
	ordinal: number;
	judgement_type_id: Id;
	time: Time;
	contest_time?: RelTime; // 2023-06 spec
	run_time: number;
	score?: number; // 2026-01-next spec
}

export interface Account {
	id: Id;
	username: string;
	password?: string;
	name?: string;
	type: 'team' | 'judge' | 'admin' | 'analyst' | 'staff' | 'coach'; // 2023-06 | 2026-01-next spec
	ip?: string;
	team_id?: Id;
	person_id?: Id;
}

export interface Clarification {
	id: Id;
	from_team_id?: Id;
	to_team_ids?: Id[]; // 2026-01 spec
	to_group_ids?: Id[]; // 2026-01 spec
	to_team_id?: Id; // 2023-06 spec
	reply_to_id?: Id;
	problem_id?: Id;
	text: string;
	time: Time;
	contest_time: RelTime;
}

export interface Commentary {
	id: Id;
	time: Time;
	contest_time: RelTime;
	message: string;
	tags: string[];
	source_id?: Id;
	team_ids?: Id[];
	problem_ids?: Id[];
	submission_ids?: Id[];
}

export interface Award {
	id: Id;
	citation: string;
	team_ids?: Id[];
	display_mode?: string; // CDS extension
}

export interface Notification {
	type: ContestType;
	id?: Id;
	data?: { id: Id }[] | object;
	token?: string;
}

// 2026-01-next spec
export interface RemovedInterval {
	start: Time;
	end?: Time;
	contest_time: RelTime;
}

// 2026-01-next spec
export interface PersonRole {
	type: 'contestant' | 'coach' | 'staff' | 'other';
	title?: string;
	team_id?: Id;
}

// CDS extension
export interface MapInfo {
	table_width: number;
	table_depth: number;
	team_area_width: number;
	team_area_depth: number;
	aisles?: Aisle[];
	spare_teams?: TeamLocation[];
	printer?: FloorLocation;
}

// CDS extension
export interface Aisle {
	x1: number;
	y1: number;
	x2: number;
	y2: number;
}

// CDS extension
export interface FloorLocation {
	x: number;
	y: number;
}

// CDS extension
export interface StartStatus {
	id: Id;
	label: string;
	status: 0 | 1 | 2;
}
