import * as ts from 'typescript';
import * as fs from 'fs';
import * as path from 'path';

const SRC_DIR = path.resolve(import.meta.dirname, '..', 'src');

interface SourceFile {
	label: string;
	comment: string;
	kind: 'full' | 'partial';
}

const SOURCES: SourceFile[] = [
	{ label: '2023-06', comment: '2023-06 spec', kind: 'full' },
	{ label: '2026-01', comment: '2026-01 spec', kind: 'full' },
	{ label: '2026-01-next', comment: '2026-01-next spec', kind: 'full' },
	{ label: 'CDS', comment: 'CDS extension', kind: 'partial' }
];

const FULL_LABELS = SOURCES.filter((s) => s.kind === 'full').map((s) => s.label);
const RENAME_MAP: Record<string, string> = { Info: 'Version' };

const HEADER = `\
/**
 * Contest API Types
 *
 * AUTO-GENERATED by scripts/merge-types.ts - DO NOT EDIT
 *
 * This file is merged from the spec-version-specific contest-types-*.ts files.
 * It includes types from the ${SOURCES.filter((s) => s.kind === 'full').map((s) => s.label)} Contest API specifications,
 * and ${SOURCES.filter((s) => s.kind === 'partial').map((s) => s.label)} extensions.
 * Inline comments are used to indicate objects and properties that are unique to any of these.
 */
`;

// --- Types ---

interface PropertyInfo {
	type: string;
	optional: boolean;
	sources: string[];
	typesBySource: Map<string, string>;
}

interface InterfaceInfo {
	heritage: string | undefined;
	properties: Map<string, PropertyInfo>;
	propertyOrder: string[];
	sources: string[];
}

interface TypeAliasInfo {
	type: string;
	sources: string[];
}

interface ParsedFile {
	source: SourceFile;
	interfaces: Map<string, InterfaceInfo>;
	typeAliases: Map<string, TypeAliasInfo>;
	declarationOrder: string[];
}

// --- Helpers ---

function mergeUnionParts(existing: string, incoming: string, multiLine: boolean): string {
	const split = (s: string) =>
		s
			.split('|')
			.map((t) => t.trim())
			.filter(Boolean);
	const existingParts = split(existing);
	for (const part of split(incoming)) {
		if (!existingParts.includes(part)) {
			existingParts.push(part);
		}
	}
	return multiLine ? '| ' + existingParts.join('\n\t| ') : existingParts.join(' | ');
}

function mergePropertyOrder(existing: string[], incoming: string[]): string[] {
	const result: string[] = [];
	const seen = new Set<string>();

	for (const name of existing) {
		if (!seen.has(name)) {
			seen.add(name);
			result.push(name);

			const idx = incoming.indexOf(name);
			if (idx >= 0) {
				for (let j = idx + 1; j < incoming.length; j++) {
					const next = incoming[j];
					if (existing.includes(next)) break;
					if (!seen.has(next)) {
						seen.add(next);
						result.push(next);
					}
				}
			}
		}
	}

	for (const name of incoming) {
		if (!seen.has(name)) {
			seen.add(name);
			result.push(name);
		}
	}

	return result;
}

function getPropertyComment(prop: PropertyInfo): string | undefined {
	const partialSources = prop.sources.filter((s) => !FULL_LABELS.includes(s));
	if (partialSources.length > 0) {
		return SOURCES.find((s) => s.label === partialSources[0])?.comment;
	}

	const fullSources = prop.sources.filter((s) => FULL_LABELS.includes(s));
	if (fullSources.length === FULL_LABELS.length) {
		const groups = new Map<string, string[]>();
		for (const label of fullSources) {
			const type = prop.typesBySource.get(label) ?? prop.type;
			const existing = groups.get(type);
			if (existing) existing.push(label);
			else groups.set(type, [label]);
		}
		if (groups.size <= 1) return undefined;

		const representatives = [...groups.values()].map((labels) => SOURCES.find((s) => labels.includes(s.label))!.label);
		return representatives.join(' | ') + ' spec';
	}

	return SOURCES.find((s) => fullSources.includes(s.label))?.comment;
}

// --- Parse ---

function parseFile(source: SourceFile): ParsedFile {
	const sourcePath = path.join(SRC_DIR, `contest-types-${source.label}.ts`);
	const content = fs.readFileSync(sourcePath, 'utf-8');
	const sf = ts.createSourceFile(sourcePath, content, ts.ScriptTarget.Latest, true);
	const interfaces = new Map<string, InterfaceInfo>();
	const typeAliases = new Map<string, TypeAliasInfo>();
	const declarationOrder: string[] = [];

	for (const stmt of sf.statements) {
		if (ts.isInterfaceDeclaration(stmt)) {
			const name = stmt.name.text;
			const propertyOrder: string[] = [];
			const properties = new Map<string, PropertyInfo>();

			let heritage: string | undefined;
			if (stmt.heritageClauses) {
				for (const clause of stmt.heritageClauses) {
					heritage = clause.types.map((t) => t.getText(sf)).join(', ');
				}
			}

			for (const member of stmt.members) {
				if (ts.isPropertySignature(member) && member.name) {
					const propName = member.name.getText(sf);
					const propType = member.type ? member.type.getText(sf) : 'any';
					const optional = !!member.questionToken;
					properties.set(propName, {
						type: propType,
						optional,
						sources: [source.label],
						typesBySource: new Map([[source.label, propType]])
					});
					propertyOrder.push(propName);
				}
			}

			interfaces.set(name, {
				heritage,
				properties,
				propertyOrder,
				sources: [source.label]
			});

			if (!declarationOrder.includes(name)) declarationOrder.push(name);
		} else if (ts.isTypeAliasDeclaration(stmt)) {
			const name = stmt.name.text;
			const type = stmt.type.getText(sf);
			typeAliases.set(name, { type, sources: [source.label] });
			if (!declarationOrder.includes(name)) declarationOrder.push(name);
		}
	}

	return { source, interfaces, typeAliases, declarationOrder };
}

// --- Merge ---

function mergeTypes(parsed: ParsedFile[]): string {
	const mergedInterfaces = new Map<string, InterfaceInfo>();
	const mergedTypeAliases = new Map<string, TypeAliasInfo>();

	for (const pf of parsed) {
		const isPartial = pf.source.kind === 'partial';

		for (const [name, ta] of pf.typeAliases) {
			if (mergedTypeAliases.has(name)) {
				const existing = mergedTypeAliases.get(name)!;
				existing.sources.push(pf.source.label);
				if (existing.type !== ta.type) {
					existing.type = mergeUnionParts(existing.type, ta.type, true);
				}
			} else {
				mergedTypeAliases.set(name, { ...ta, sources: [pf.source.label] });
			}
		}

		for (const [name, iface] of pf.interfaces) {
			if (mergedInterfaces.has(name)) {
				const existing = mergedInterfaces.get(name)!;
				if (!isPartial) existing.sources.push(pf.source.label);

				for (const [propName, prop] of iface.properties) {
					if (existing.properties.has(propName)) {
						const ep = existing.properties.get(propName)!;
						ep.typesBySource.set(pf.source.label, prop.type);

						ep.sources.push(pf.source.label);
						if (ep.type !== prop.type) {
							ep.type = mergeUnionParts(ep.type, prop.type, false);
						}
						if (prop.optional) ep.optional = true;
					} else {
						existing.properties.set(propName, {
							...prop,
							optional: isPartial ? true : prop.optional,
							sources: [pf.source.label],
							typesBySource: new Map([[pf.source.label, prop.type]])
						});
					}
				}

				existing.propertyOrder = mergePropertyOrder(existing.propertyOrder, iface.propertyOrder);
			} else {
				const clonedProps = new Map<string, PropertyInfo>();
				for (const [propName, prop] of iface.properties) {
					clonedProps.set(propName, {
						...prop,
						sources: [pf.source.label],
						typesBySource: new Map([[pf.source.label, prop.type]])
					});
				}
				mergedInterfaces.set(name, {
					...iface,
					properties: clonedProps,
					propertyOrder: [...iface.propertyOrder],
					sources: [pf.source.label]
				});
			}
		}
	}

	// Make properties not in all full files optional
	for (const [, iface] of mergedInterfaces) {
		if (iface.sources.length <= 1) continue;
		for (const [, prop] of iface.properties) {
			const inFull = prop.sources.filter((s) => FULL_LABELS.includes(s));
			if (inFull.length > 0 && inFull.length < FULL_LABELS.length && !prop.optional) {
				prop.optional = true;
			}
		}
	}

	// Build declaration order from SOURCES order
	const declarationOrder: string[] = [];
	for (const pf of parsed) {
		for (const name of pf.declarationOrder) {
			if (!declarationOrder.includes(name)) declarationOrder.push(name);
		}
	}

	// --- Emit ---

	const lines: string[] = [HEADER];

	for (const name of declarationOrder) {
		const outputName = RENAME_MAP[name] ?? name;

		if (mergedTypeAliases.has(name)) {
			const ta = mergedTypeAliases.get(name)!;
			if (ta.type.includes('\n')) {
				lines.push(`export type ${outputName} =\n\t${ta.type};\n`);
			} else {
				lines.push(`export type ${outputName} = ${ta.type};\n`);
			}
			continue;
		}

		if (mergedInterfaces.has(name)) {
			const iface = mergedInterfaces.get(name)!;
			const inAllFull = FULL_LABELS.every((fl) => iface.sources.includes(fl));

			if (!inAllFull) {
				const partialSources = iface.sources.filter((s) => !FULL_LABELS.includes(s));
				const src =
					partialSources.length > 0
						? SOURCES.find((s) => s.label === partialSources[0])
						: SOURCES.find((s) => iface.sources.includes(s.label));
				lines.push(`// ${src?.comment}`);
			}

			const heritage = iface.heritage ? ` extends ${iface.heritage}` : '';
			lines.push(`export interface ${outputName}${heritage} {`);

			for (const propName of iface.propertyOrder) {
				const prop = iface.properties.get(propName);
				if (!prop) continue;
				const opt = prop.optional ? '?' : '';
				const comment = inAllFull ? getPropertyComment(prop) : undefined;
				const commentStr = comment ? ` // ${comment}` : '';
				lines.push(`\t${propName}${opt}: ${prop.type};${commentStr}`);
			}

			lines.push(`}\n`);
		}
	}

	return lines.join('\n');
}

// --- Main ---

const parsed = SOURCES.map((s) => parseFile(s));
const output = mergeTypes(parsed);
const outputPath = path.join(SRC_DIR, 'contest-types.ts');
fs.writeFileSync(outputPath, output, 'utf-8');
console.log(`Generated ${outputPath}`);
